import { HttpStatus } from "@nestjs/common";

export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH.TOKEN_EXPIRED',
  ORG_FORBIDDEN: 'ORG.FORBIDDEN',
  FORBIDDEN: 'FORBIDDEN',
  AGENT_NOT_FOUND: 'AGENT.NOT_FOUND',
  AGENT_CORE_TIMEOUT: 'AGENT_CORE.TIMEOUT',
  AGENT_CORE_UNAVAILABLE: 'AGENT_CORE.UNAVAILABLE',
  VALIDATION_FAILED: 'VALIDATION.FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  GONE: 'GONE',
  INTERNAL_UNEXPECTED: 'INTERNAL.UNEXPECTED',
  AGENT_ORIGIN_REQUIRED: 'AGENT.ORIGIN_REQUIRED',
  AGENT_ORIGIN_NOT_PERMITTED: 'AGENT.ORIGIN_NOT_PERMITTED',
  RESOURCE_NOT_FOUND: 'RESOURCE.NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE.CONFLICT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

const DefaultErrorCodeByStatus: Partial<Record<number, ErrorCode>> = {
  [HttpStatus.BAD_REQUEST]: ErrorCode.VALIDATION_FAILED,
  [HttpStatus.UNAUTHORIZED]: ErrorCode.UNAUTHORIZED,
  [HttpStatus.FORBIDDEN]: ErrorCode.FORBIDDEN,
  [HttpStatus.NOT_FOUND]: ErrorCode.RESOURCE_NOT_FOUND,
  [HttpStatus.CONFLICT]: ErrorCode.RESOURCE_CONFLICT,
};

export function defaultErrorCodeForStatus(status: number): ErrorCode {
  return DefaultErrorCodeByStatus[status] ?? ErrorCode.INTERNAL_UNEXPECTED;
}