import {
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  JoinColumn,
  BeforeInsert,
  OneToMany,
} from "typeorm";
import { uuidv7 } from "uuidv7";
import { Agent } from "../../agents/entities/agent.entity";
import { Message } from "./message.entity";

export enum ConversationStatus {
  ACTIVE = "active",
  ENDED = "ended",
  ERROR = "error",
}

@Entity("conversations")
export class Conversation {
  @PrimaryColumn({ type: "uuid" })
  id: string;

  @Column({ type: "uuid", name: "agent_id" })
  agentId: string;

  // Generated by the widget on first load — ties messages across page refreshes
  @Column({ type: "varchar", length: 255, name: "session_id" })
  sessionId: string;

  // Optional: populated when the embedding site has authenticated users
  @Column({ type: "varchar", length: 255, name: "end_user_id", nullable: true })
  endUserId: string;

  @Column({ type: "int", name: "total_tokens", default: 0 })
  totalTokens: number;

  @Column({ type: "int", name: "message_count", default: 0 })
  messageCount: number;

  @Column({
    type: "varchar",
    length: 50,
    default: ConversationStatus.ACTIVE,
  })
  status: ConversationStatus;

  @CreateDateColumn({ name: "started_at", type: "timestamptz" })
  startedAt: Date;

  @Column({ type: "timestamptz", name: "last_message_at", nullable: true })
  lastMessageAt: Date;

  @ManyToOne(() => Agent, { onDelete: "CASCADE" })
  @JoinColumn({ name: "agent_id" })
  agent: Agent;

  @OneToMany(() => Message, (message) => message.conversation)
  messages: Message[];

  @BeforeInsert()
  generateId() {
    if (!this.id) this.id = uuidv7();
  }
}
